### PR TITLE
Populate variables into custom theme template markup

### PR DESCRIPTION
**Pull request by KevinBrent**
## Changes
* Populate variables into custom theme template markup

## Testing instructions
1. Add a custom theme template
2. Add block to page and assign values to variables
3. Load block on frontend

### CODE REVIEW

**Comment by kienstra** [comment]
Hi @KevinBrent,
Thanks for opening this. Could you help with the reasoning behind this?

To be honest, it's not too likely that we'll change a core part of the plugin without a big need.

Thanks!

**Comment by KevinBrent** [comment]
Hello,

Thanks for your question.

We have many sites that use the same theme that includes the block templates. When we update our block template structure, we do so and track changes in our git repos. Since the current version of this plugin stores these templates in the database. We are required to manually update all the databases for all the sites with every change. This is a very tedious and time consuming task. 

The solution we propose solves both issues. 
Allows for version control
Provides a more productive templating solution

We hope you find these issues valuable enough to implement this or another similar solution.

Kevin Brent

**Comment by kienstra** [comment]
Hi @KevinBrent,
Thanks for your details!

>Since the current version of this plugin stores these templates in the database.

Hm, it sounds like the sites aren't using [PHP templates for Genesis Custom Blocks](https://developer.wpengine.com/genesis-custom-blocks/get-started/add-a-custom-block-to-your-website-content/).

**Comment by KevinBrent** [comment]
We did not see this documentation. We can use the block_field() function for the solution.

Sorry for the inconvenience.

Kevin Brent

**Comment by kienstra** [comment]
@KevinBrent,
Oh all good, it's a huge compliment that you're using Genesis Custom Blocks! 

The fact that it means enough to you to submit PRs is huge!

**Pull request closed without merging**
