### PR TITLE
Test with WP `6.4`

### PR DESCRIPTION
**Pull request by kienstra**
## Changes
* Test with WP `6.4`

## Testing instructions
Not needed

### CODE REVIEW

**Comment by Jeffrey-H** [comment]
I have the following javascript error for each component on a page while editing this in the admin side of WordPress.

```
react-dom.min.js?ver=18.2.0:10 TypeError: Cannot read properties of undefined (reading 'debounce')
    at r.value (block-editor.js?ver=cb388836d4d4ac05b12a:1:85808)
    at Jr (react-dom.min.js?ver=18.2.0:10:80714)
    at Zr (react-dom.min.js?ver=18.2.0:10:80489)
    at Gr (react-dom.min.js?ver=18.2.0:10:80023)
    at react-dom.min.js?ver=18.2.0:10:91526
    at xl (react-dom.min.js?ver=18.2.0:10:92039)
    at fl (react-dom.min.js?ver=18.2.0:10:85808)
    at Nn (react-dom.min.js?ver=18.2.0:10:32474)
    at El (react-dom.min.js?ver=18.2.0:10:93374)
    at react-dom.min.js?ver=18.2.0:10:89834
    ```

**Comment by kienstra** [comment]
Hi @Jeffrey-H,
Thanks for letting me know.

If you don't mind me asking, what theme are you running, and are there other plugins active?

**Comment by Jeffrey-H** [comment]
@kienstra 

Ofcourse, no problem at all. A couple of small plugins, nothing with page breaking features.
image

I'm running Twenty Twenty-Three version: 1.3

Good to mention, the error above is on the admin side :)

**Comment by kienstra** [comment]
Thanks, Jeffrey. Nothing unusual in your setup.

**Pull request closed without merging**
