### PR TITLE
Add a JS filter for a preview other than the <ServerSideRender>

### PR DESCRIPTION
**Pull request by kienstra**
#### Changes
* This allows GCB to be used in [headless](https://github.com/kienstra/headless-blocks)
* Now, users can define their own React preview component
* But even if this filter isn't used much, it probably won't hurt to add it

#### Testing instructions
1. For this PR, do `composer install && npm install && npm run dev`
2. Upload and activate this plugin on `/wp-admin/plugin-install.php`: 
[headless-blocks.0.1.0.zip](https://github.com/studiopress/genesis-custom-blocks/files/6058916/headless-blocks.0.1.0.zip)
3. That [plugin](https://github.com/kienstra/headless-blocks) is the 'headless connector' for GCB, and will add alternate previews
4. `/wp-admin` > Posts > Add New
5. Add an 'Email Opt In' block that `headless-blocks` registered
6. Populate the fields: 
the-block-in-g
7. Click outside the block so the preview shows
8. Expected: The preview is a React component, using the new JS filter `genesisCustomBlocks.alternatePreview`:  
the-preview

### CODE REVIEW

**Comment by kienstra** [comment]
Here's a built `.zip` of this branch to install:
[genesis-custom-blocks.1.1.0.zip](https://github.com/studiopress/genesis-custom-blocks/files/6026023/genesis-custom-blocks.1.1.0.zip)

**Review by RobStino — APPROVED** [review]
Hey.
This makes sense to me, but I'd recommend someone else do a code review if needed.
My only thought is to having this filter:
`genesisCustomBlocks.alternatePreview`
as perhaps:
`genesisCustomBlocks.reactPreview`
But that's just a suggestion.

**Comment by kienstra** [comment]
Hi @RobStino,
Thanks a lot!

>This makes sense to me, but I'd recommend someone else do a code review if needed.

Sounds good.

>`genesisCustomBlocks.reactPreview`

Good idea, I'll change that.

**Comment by kienstra** [comment]
Closing, as there's no plan to develop `headless-blocks` anymore.

**Pull request closed without merging**
