### PR TITLE
Add Rob's copy to the readme

### PR DESCRIPTION
**Pull request by kienstra**
#### Changes
* Applies Rob's copy

#### Testing instructions
1. `npm install --global gulp-cli` # if you haven't already
2. `npm install && gulp`
3. Expected: When copying `package/trunk/readme.txt` into the [readme validator](https://wordpress.org/plugins/developers/readme-validator/), there should only be these notices:

```
No == Upgrade Notice == section was found
No == Screenshots == section was found
No donate link was found
```

### CODE REVIEW

**Comment by kienstra** [comment]
Hi @RobStino and @lukecarbis,
Could you please review this? 

It applies Rob's `readme` copy and images.

The [screenshot-*.png images](https://github.com/studiopress/genesis-custom-blocks/pull/24/files?short_path=367c5c6#diff-367c5c6c6b53205eb1173ea5993ab3ff) look like they have space around them:

empty-space-here

Not sure if it needs a change, but feel free to commit to this PR if so.

Thanks!

**Comment by kienstra** [comment]
Here's the `readme.txt`:

```
=== Genesis Custom Blocks ===

Contributors: lukecarbis, ryankienstra, Stino11, rheinardkorf, studiopress, wpengine
Tags: gutenberg, blocks, block editor, fields, template
Requires at least: 5.0
Tested up to: 5.5
Requires PHP: 5.6
Stable tag: 1.0.0
License: GPLv2 or later
License URI: http://www.gnu.org/licenses/gpl

Custom blocks for WordPress made easy.

== Description ==

Genesis Custom Blocks Pro provides WordPress developers with the tools they need to take control of the block-first reality of modern WordPress.

The WordPress block editor (AKA Gutenberg) opens up a whole new world for the way we build pages, posts, and websites with WordPress. Genesis Custom Blocks Pro makes it easy to harness this and build custom blocks the way you want them to be built. Whether you want to implement a custom design, deliver unique functionality, or even remove your dependence on other plugins, Genesis Custom Blocks Pro equips you with the tools you need to hit “Publish” sooner.

**Take control of design** - Implement beautiful, custom designs with fine-tuned front-end templating control.

**Build unique functionality** - Build blocks that function and behave exactly as you need.

**Extend & Integrate** - Easily extend your custom blocks to integrate with third-party apps and plugins.

== Features ==

= A Familiar Experience =
Work within the WordPress admin with an interface you already know.

= Block Fields =
Add from a growing list of available fields to your custom blocks.

= Simple Templating =
Let the plugin do the heavy lifting so you can use familiar WordPress development practices to build block templates.

= Developer Friendly Functions =
Simple to use functions, ready to render and work with the data stored through your custom block fields.

== Currently available block fields ==
* Text Field
* Image Field
* URL Field
* Toggle Field
* Textarea Field
* Select Field
* Range Rield
* Radio Field
* Number Field
* Multi-select Field
* Email Field
* Color Field
* Checkbox Field

== Do more with Genesis Pro ==
For those wanting to level-up with Genesis Custom Blocks, a Genesis Pro subscription brings some serious power-user features:

= Genesis Custom Blocks Pro Features =
* Repeater Field
* Taxonomy Field
* Post Field
* User Field
* Rich Text Field
* Classic Text Field
* Block Level Import/Export
* 24/7 Support

Genesis Pro includes even more value for modern WordPress content creators, marketers, and developers. [Learn more about Genesis Pro here](https://www.studiopress.com/genesis-pro/).

== Developer docs you can rely on. ==
Developer tools are only as good as their docs. That's why we take them seriously. Here are a few links to get you started:
* [Getting Started](https://developer.wpengine.com/genesis-custom-blocks/get-started/)
* [FAQs](https://developer.wpengine.com/genesis-custom-blocks/faqs/)
* [Block Fields](https://developer.wpengine.com/genesis-custom-blocks/fields/)
* [PHP Functions](https://developer.wpengine.com/genesis-custom-blocks/functions/)

== Installation ==
This plugin can be installed directly from your site.
1. Log in and navigate to Plugins → Add New.
2. Type “Genesis Custom Blocks” into the Search and hit Enter.
3. Locate the Genesis Custom Blocks plugin in the list of search results and click Install Now.
4. Once installed, click the Activate link.

It can also be installed manually.
1. Download the Genesis Custom Blocks plugin from WordPress.org.
2. Unzip the package and move to your plugins directory.
3. Log into WordPress and navigate to the Plugins screen.
4. Locate Genesis Custom Blocks in the list and click the Activate link.

== Frequently Asked Questions ==
**Q: Do I need to work with the Genesis Framework or any of the other Genesis plugins/themes to use this plugin?**
A: No. You can use this plugin completely independently. All you need is to have the block editor enabled on your WordPress site.

== Links ==
* [WordPress.org](https://wordpress.org/plugins/genesis-custom-blocks)
* [GitHub](https://github.com/studiopress/genesis-custom-blocks)
* [Documentation](https://developer.wpengine.com/genesis-custom-blocks)

== Changelog ===

= 1.0.0 - 2020-09-01 =

Plugin released!

* Easily create custom blocks
* 13 fields to add
* Simple templating, with PHP files

```

**Comment by kienstra** [comment]
New `readme.txt` build:

```
=== Genesis Custom Blocks ===

Contributors: lukecarbis, ryankienstra, Stino11, rheinardkorf, studiopress, wpengine
Tags: gutenberg, blocks, block editor, fields, template
Requires at least: 5.0
Tested up to: 5.5
Requires PHP: 5.6
Stable tag: 1.0.0
License: GPLv2 or later
License URI: http://www.gnu.org/licenses/gpl

Custom blocks for WordPress made easy.

== Description ==

Genesis Custom Blocks provides WordPress developers with the tools they need to take control of the block-first reality of modern WordPress.

The WordPress block editor (AKA Gutenberg) opens up a whole new world for the way we build pages, posts, and websites with WordPress. Genesis Custom Blocks makes it easy to harness this and build custom blocks the way you want them to be built. Whether you want to implement a custom design, deliver unique functionality, or even remove your dependence on other plugins, Genesis Custom Blocks equips you with the tools you need to hit “Publish” sooner.

**Take control of design** - Implement beautiful, custom designs with fine-tuned front-end templating control.

**Build unique functionality** - Build blocks that function and behave exactly as you need.

**Extend & Integrate** - Easily extend your custom blocks to integrate with third-party apps and plugins.

== Features ==

= A Familiar Experience =
Work within the WordPress admin with an interface you already know.

= Block Fields =
Add from a growing list of available fields to your custom blocks.

= Simple Templating =
Let the plugin do the heavy lifting so you can use familiar WordPress development practices to build block templates.

= Developer Friendly Functions =
Simple to use functions, ready to render and work with the data stored through your custom block fields.

== Currently available block fields ==
* Text Field
* Image Field
* URL Field
* Toggle Field
* Textarea Field
* Select Field
* Range Rield
* Radio Field
* Number Field
* Multi-select Field
* Email Field
* Color Field
* Checkbox Field

== Do more with Genesis Pro ==
For those wanting to level-up with Genesis Custom Blocks, a Genesis Pro subscription brings some serious power-user features:

= Genesis Custom Blocks Pro Features =
* Repeater Field
* Taxonomy Field
* Post Field
* User Field
* Rich Text Field
* Classic Text Field
* Block Level Import/Export
* 24/7 Support

Genesis Pro includes even more value for modern WordPress content creators, marketers, and developers. [Learn more about Genesis Pro here](https://www.studiopress.com/genesis-pro/).

== Developer docs you can rely on. ==
Developer tools are only as good as their docs. That's why we take them seriously. Here are a few links to get you started:
* [Getting Started](https://developer.wpengine.com/genesis-custom-blocks/get-started/)
* [FAQs](https://developer.wpengine.com/genesis-custom-blocks/faqs/)
* [Block Fields](https://developer.wpengine.com/genesis-custom-blocks/fields/)
* [PHP Functions](https://developer.wpengine.com/genesis-custom-blocks/functions/)

== Installation ==
This plugin can be installed directly from your site.
1. Log in and navigate to Plugins → Add New.
2. Type “Genesis Custom Blocks” into the Search and hit Enter.
3. Locate the Genesis Custom Blocks plugin in the list of search results and click Install Now.
4. Once installed, click the Activate link.

It can also be installed manually.
1. Download the Genesis Custom Blocks plugin from WordPress.org.
2. Unzip the package and move to your plugins directory.
3. Log into WordPress and navigate to the Plugins screen.
4. Locate Genesis Custom Blocks in the list and click the Activate link.

== Frequently Asked Questions ==
**Q: Do I need to work with the Genesis Framework or any of the other Genesis plugins/themes to use this plugin?**
A: No. You can use this plugin completely independently. All you need is to have the block editor enabled on your WordPress site.

== Links ==
* [WordPress.org](https://wordpress.org/plugins/genesis-custom-blocks)
* [GitHub](https://github.com/studiopress/genesis-custom-blocks)
* [Documentation](https://developer.wpengine.com/genesis-custom-blocks)

== Changelog ===

= 1.0.0 - 2020-09-01 =

Plugin released!

* Easily create custom blocks
* 13 fields to add
* Simple templating, with PHP files

```

**Comment by kienstra** [comment]
Hi @RobStino,
Thanks for the screenshots, most of them look good.

Does the [screeenshot-1.png](https://github.com/studiopress/genesis-custom-blocks/pull/24/files?short_path=367c5c6#diff-367c5c6c6b53205eb1173ea5993ab3ff) still have a shadow?

**Comment by RobStino** [comment]
Hi @kienstra 
Thanks for this work. 
2 issues and 1 question:
**Issues**
1. The wp readme validator is showing an issue with a `ul`
image

2. The wp readme validator is showing that the installation instructions are being doubled-up down in the FAQ section
image

**Question**
1. Are you saying that you are seeing a shadow on one of those images still? There should be no shadows on any of them.

**Comment by RobStino** [comment]
@kienstra In response to my own question above, here are the 4 screenshot images. I'm guessing one of the ones I sent you the other day didn't export properly or something.
screenshot-1
screenshot-2
screenshot-3
screenshot-4

**Comment by lukecarbis** [comment]
@RobStino Please re-review. I fixed the list issue and updated `screenshot-1.png` to a version that doesn't have a shadow.

As for the FAQ showing installation instructions, I'm guessing that's a quirk of wpreadme.com. The way this readme includes installation instructions is exactly the same as Block Lab does, and that doesn't show up in the FAQ on .org.

**Review by RobStino — APPROVED** [review]
Done!

**Pull request merged**
