### PR TITLE
Remove white space under color setting in sidebar

### PR DESCRIPTION
**Pull request by pesonn**
- [x] I have signed the [Contributor License Agreement](https://wpeng.in/cla/) with WP Engine.

## Changes
* Remove height for color base control, as it's increasing the height and other settings get moved out of the sidebar.

## Testing instructions
Example: 
Genesis Custom Blocks Color Setting

### CODE REVIEW

**Comment by kienstra** [comment]
Hi @pesonn,
Thanks for opening this.

Do you see this bug without the Gutenberg plugin active?

Without Gutenberg active, with Core `6.3.2`, and Genesis Custom Blocks `develop` branch I don't see any problem:

Screenshot 2023-10-30 at 12 11 16 PM

But I do see the same problem as in [your screenshot](https://github.com/studiopress/genesis-custom-blocks/pull/163#issue-1961542294) with Gutenberg active.

**Comment by pesonn** [comment]
> 
> Do you see this bug without the Gutenberg plugin active?
> 

@kienstra Could you just help me and give me a hint on disable Gutenberg without returning back to the classic editor?

**Comment by kienstra** [comment]
Hi @pesonn,
There's no need to disable Gutenberg (the block editor), just the [Gutenberg plugin](https://wordpress.org/plugins/gutenberg).

**Comment by pesonn** [comment]
@kienstra As we did installed the Gutenberg plugin, I installed it and deactivated it again. Seemed a little wrong. Was that what you meant? 
With deactivated Gutenberg Plugin the space was still there.

**Comment by kienstra** [comment]
Hi @pesonn,

>Was that what you meant?

Yes. Sorry for the delay getting back to you.

I can't replicate the issue. 

1. `git checkout develop; nvm use; npm ci; composer i; npm run build`
2. Create a block with a color field in the Inspector, and something else below it:

Screenshot 2023-11-06 at 11 09 33 AM


3. Publish that block
4. Create a new post
5. Add that block to the post
6. Expected and actual: There's no space below the color field:
Screenshot 2023-11-06 at 11 04 26 AM

**Pull request closed without merging**
