### PR TITLE
Remove the Changelog section, simply link to GitHub Releases page

### PR DESCRIPTION
**Pull request by kienstra**
## Changes
* Remove the Changelog section
* Simply links to GH Releases page
* Makes releases easier. Why have essentially 2 Changelogs: the README.md Changelog and the [GitHub Releases page](https://github.com/studiopress/genesis-custom-blocks/releases)?

## Testing instructions
Not needed

### CODE REVIEW

**Review by mike-day — APPROVED** [review]
This is a good idea! You are right — there is not much point in updating a changelog in two places.

**Comment by kienstra** [comment]
Thanks so much, @mike-day!

**Comment by Surbma** [comment]
> there is not much point in updating a changelog in two places.

The changelog in the readme.txt file is used by other services, like WP management services to display the changes. So it is very useful to have it in its place. ;)

**Comment by kienstra** [comment]
Hi @Surbma,
Thanks for letting me know, I didn't think about that.

**Comment by kienstra** [comment]
Is the link not visible in places like "WP management services"?

**Comment by Surbma** [comment]
> Is the link not visible in places like "WP management services"?

No link, only the text. So I need to find the plugin in the WP repo, than click on the Development tab, than click on the link to actually see the changelog.

**Comment by kienstra** [comment]
Oh wow, so it sounds like it strips the link entirely. That's not good.

**Pull request merged**
